---
sidebar: sidebar 
permalink: analyze-error-logs.html 
keywords: analyze error logs, errors, error severity, Microsoft SQL Server error logs, smart analysis, Agentic AI 
summary: 데이터베이스의 워크로드 팩토리 내에서 오류 로그를 분석합니다. 
---
= 워크로드 팩토리에서 오류 로그 분석
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
스마트 오류 로그 분석기를 사용하면 Microsoft SQL Server 오류 로그를 자동으로 해석하여 문제를 빠르게 식별하고 해결할 수 있습니다.  Agentic AI 기반 분석에는 Amazon Bedrock 통합이 필요합니다.

.이 작업에 대해
오류 로그 분석 및 수정은 SQL Server 인스턴스의 상태와 성능을 유지하는 데 도움이 됩니다.  SQL Server 오류 로그를 효과적으로 해석하려면 신중한 분석과 전문 지식이 필요합니다.  수동 모니터링, 오류 감지, 근본 원인 분석은 시간이 많이 걸리고 오류가 발생하기 쉽습니다.  이러한 과제로 인해 문제 해결이 지연되고, 가동 중지 시간이 늘어나고, 운영상의 비효율성이 발생할 수 있습니다.  스마트 오류 로그 분석기는 다음과 같은 주요 이점을 통해 이러한 과제를 해결합니다.

* 스마트 그룹화: 오류를 고유성, 심각도, 범주별로 지능적으로 통합하고 문제 해결 프로세스를 간소화하여 더 빠르고 효과적인 해결책을 제공합니다.
* AI 기반 조사: AI를 활용하여 오류를 사전에 분석하고, 심층적인 전문 지식 없이도 문제를 더 빨리 식별할 수 있는 명확하고 실행 가능한 통찰력을 제공합니다.
* 오류 보강: 외부 참조로 오류 로그를 보강하여 맥락적 명확성을 제공하고 이해와 의사 결정을 개선합니다.
* 모범 사례 수정: FSx for ONTAP 에서 실행되는 SQL Server 워크로드에 맞춤형 수정 권장 사항을 제공하여 모든 기술 수준의 사용자가 자신 있게 문제를 해결할 수 있도록 지원합니다.


스마트 오류 로그 분석기를 사용하면 고급 AI 분석의 이점을 누리는 동시에 환경을 완벽하게 제어할 수 있습니다.

스마트 오류 로그 분석기를 사용하려면 Amazon Bedrock을 활성화하고, 워크로드 팩토리에서 사용하는 모델을 선택하고, Amazon Bedrock에 연결할 개인 엔드포인트를 만들고, 권한을 추가하고, 엔터프라이즈 라이선스를 만들어야 합니다.

link:https://aws.amazon.com/bedrock/pricing/["Amazon Bedrock 가격"^]

.시작하기 전에
Smart Error Log Analyzer를 사용하려면 다음 전제 조건을 충족해야 합니다.

* 작업 부하 공장에서 새 데이터베이스 호스트를 생성해야 link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정 자격 증명 및 _읽기/쓰기_ 모드 권한"^]합니다.
* link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["SQL Server 인스턴스 등록"^]작업 부하 공장에서. *


.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. 데이터베이스에서 * Inventory * 탭을 선택합니다.
. 데이터베이스 엔진으로 *SQL Server*를 선택합니다.
. 인스턴스 탭에서 분석하려는 특정 SQL Server 인스턴스를 찾은 다음 메뉴에서 *오류 조사*를 선택합니다.
. *오류 조사* 탭에서 콘솔에 설명된 대로 다음 필수 조건을 완료하세요.
+
** 아마존 베드락
** 네트워킹: Amazon Bedrock의 개인 엔드포인트
** EC2 인스턴스 프로필 역할에 대한 권한
** 워크로드 데이터베이스 관리(wlmdb)와 관련된 자격 증명


. 필수 조건을 충족하면 *지금 조사*를 선택하여 스마트 오류 로그 분석기를 사용하여 SQL Server 오류 로그에 대한 통찰력을 얻으세요.
+
검사 후에는 콘솔에 오류가 표시되어 Smart error log analysis에서 감지된 문제에 대한 포괄적인 보기를 제공합니다.

. 심각도, 기간, 오류 코드 등의 기준에 따라 표시되는 오류를 필터링하여 구체화합니다.
. 원래 오류 메시지, AI 기반 설명, 오류를 해결하기 위한 제안된 수정 단계를 포함한 자세한 오류 정보를 검토하세요.

