---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: 데이터베이스에 대한 BlueXP  워크로드 팩토리 내에서 새 PostgreSQL SQL Server를 생성합니다. 
---
= BlueXP  워크로드 팩터리에서 PostgreSQL 서버를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 공장에서 데이터베이스용 새 PostgreSQL 서버 또는 데이터베이스 호스트를 생성하려면 Active Directory를 위한 FSx for ONTAP 파일 시스템 구축 및 리소스가 필요합니다.

.이 작업에 대해
BlueXP  워크로드 팩토리로부터 PostgreSQL 서버를 생성하기 전에 데이터베이스 호스트 구성에 사용할 수 있는 스토리지 구축 유형, 워크로드 팩토리 작동 모드 및 이 작업을 완료하기 위한 요구 사항에 대해 알아보십시오.

FSx for ONTAP 파일 시스템 배포:: 새 PostgreSQL 서버를 생성하려면 스토리지 백엔드로 FSx for ONTAP 파일 시스템이 필요합니다. 기존 FSx for ONTAP 파일 시스템을 사용하거나 새 파일 시스템을 생성할 수 있습니다. 기존 FSx for ONTAP 파일 시스템을 데이터베이스 서버 스토리지 백엔드로 선택하면 PostgreSQL 워크로드에 대한 새 스토리지 VM이 생성됩니다.
+
--
FSx for ONTAP 파일 시스템에는 두 가지 PostgreSQL 서버 배포 모델(_HA(고가용성)_ 또는 _single instance_)이 있습니다. 선택한 FSx for ONTAP 배포 모델에 따라 FSx for ONTAP 파일 시스템에 대해 다양한 리소스가 생성됩니다.

* * 고가용성(HA) 배포 *: HA 배포를 위해 새로운 FSx for ONTAP 파일 시스템을 선택하면 다중 가용성 영역 FSx for NetApp ONTAP 파일 시스템이 구축됩니다. HA 구축 환경에서는 데이터, 로그 및 tempdb 파일용으로 별도의 볼륨과 LUN이 생성됩니다. Windows 클러스터용 쿼럼 또는 감시 디스크에 대해 추가 볼륨 및 LUN이 생성됩니다. HA 배포는 기본 및 보조 PostgreSQL 서버 간의 스트리밍 복제를 구성합니다.
* * 단일 인스턴스 배포 *: 새 PostgreSQL 서버가 생성될 때 단일 가용성 영역 FSx for ONTAP 파일 시스템이 생성됩니다. 또한 데이터, 로그 및 tempdb 파일용으로 별도의 볼륨과 LUN이 생성됩니다.


--
워크로드 공장 작동 모드:: 워크로드 공장 은 워크로드 공장에서 AWS 리소스를 얼마나 편리하게 관리할 수 있는지에 따라 세 가지 운영 모드를 제공합니다.
+
--
*_Basic_mode *: 이 작업 모드에서는 작업 부하 공장에서 AWS 계정 자격 증명을 연결할 필요가 없습니다. 코드박스에서 부분적으로 채워진 YAML 템플릿을 복사하거나 다운로드하여 작업 부하 공장 외부에서 완료할 수 있습니다.

*_읽기_모드 * : 이 작업 모드에서, 귀하는 AWS 계정 자격 증명에 읽기 권한을 부여하여 _빠른 생성_또는_고급 생성_양식을 완성한 다음 복사 또는 다운로드할 수 있습니다. 또한 완료된 양식 세부 정보가 포함된 워크로드 팩토리로부터 CloudFormation으로 리디렉션할 수 있습니다. 또한 워크로드 공장에서 배포된 데이터베이스 서버를 관리할 수 있습니다.

*_AUTOMATE_MODE *: 이 작업 모드에서 AWS 계정 자격 증명에 자동화 권한을 제공하여 워크로드 공장 내에서 AWS 리소스를 생성하고 관리할 수 있습니다.

--


.시작하기 전에
새 데이터베이스 호스트를 생성하기 전에 다음과 같은 사전 요구 사항이 있는지 확인하십시오.

자격 증명 및 권한:: 작업 부하 공장에서 새 데이터베이스 호스트를 생성해야 link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정 자격 증명 및 모드 권한 자동화"^]합니다.




== 데이터베이스 서버를 만듭니다

Advanced create_deployment 모드를 사용하면 _automate_mode 권한을 사용하여 워크로드 팩토리얼에서 이 작업을 완료할 수 있습니다. 또한 코드상자에서 제공되는 REST API, AWS CLI, AWS CloudFormation 및 Terraform 툴을 사용할 수 있습니다. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["자동화를 위해 Codebox를 사용하는 방법을 알아보십시오"^]..


NOTE: Codebox에서 Terraform을 사용할 때 복사하거나 다운로드하는 코드는 숨겨지고 암호가 숨겨집니다. `fsxadmin` `vsadmin` 코드를 실행할 때 암호를 다시 입력해야 합니다. _AUTOMATE_MODE 권한 외에 사용자 계정에 대해 다음 권한을 포함해야 합니다 `iam:TagRole` `iam:TagInstanceProfile`. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#use-terraform-from-codebox["Codebox에서 Terraform을 사용하는 방법에 대해 알아봅니다"^]..

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Databases(데이터베이스) 타일에서 * Deploy database host * 를 선택한 다음 드롭다운 메뉴에서 * PostgreSQL Server * 를 선택합니다.
. Advanced create * 를 선택합니다.
. 배포 모델 * 에서 * 독립 실행형 인스턴스 * 또는 * 고가용성(HA) * 을 선택합니다.
. Landing zone * 아래에 다음을 제공합니다.
+
.. * AWS 자격 증명 *: 새 데이터베이스 호스트를 배포하려면 자동화 권한이 있는 AWS 자격 증명을 선택합니다.
+
AWS 자격 증명을 _automate_permissions 로 설정하면 워크로드 공장 내에서 AWS 계정에서 새 데이터베이스 호스트를 구축하고 관리할 수 있습니다.

+
read_permissions를 포함한 AWS 자격 증명을 통해 워크로드 공장에서 AWS CloudFormation 콘솔에서 사용할 CloudFormation 템플릿을 생성할 수 있습니다.

+
작업 부하 공장에서 연결된 AWS 자격 증명이 없고 작업 부하 공장에서 새 서버를 생성하려면 * 옵션 1 * 을 따라 자격 증명 페이지로 이동합니다. 데이터베이스 워크로드에 대해 _AUTOMATE_MODE에 필요한 자격 증명 및 권한을 수동으로 추가합니다.

+
AWS CloudFormation에서 배포할 전체 YAML 파일 템플릿을 다운로드할 수 있도록 워크로드 팩토리에서의 새 서버 만들기 양식을 작성하려면 * 옵션 2 * 를 따라 AWS CloudFormation 내에서 새 서버를 만드는 데 필요한 권한이 있는지 확인하십시오. 데이터베이스 워크로드에 대해 _READ_MODE에 필요한 자격 증명 및 권한을 수동으로 추가합니다.

+
필요한 경우 코드박스에서 부분적으로 완성된 YAML 파일 템플릿을 다운로드하여 자격 증명이나 권한 없이 워크로드 팩토리 외부에 스택을 만들 수 있습니다. 코드 상자의 드롭다운에서 * CloudFormation * 을 선택하여 YAML 파일을 다운로드합니다.

.. * 지역 및 VPC *: 지역 및 VPC 네트워크를 선택합니다.
+
기존 인터페이스 끝점에 대한 보안 그룹이 선택한 서브넷에 대한 HTTPS(443) 프로토콜에 대한 액세스를 허용하는지 확인합니다.

+
AWS 서비스 인터페이스 엔드포인트(SQS, FSx, EC2, CloudWatch, Cloud Formation, SSM) 및 S3 게이트웨이 끝점은 배포 중에 찾을 수 없는 경우 생성됩니다.

+
VPC DNS 속성 `EnableDnsSupport` 및 `EnableDnsHostnames` 이(가) 으로 설정되어 있지 않은 경우 엔드포인트 주소 확인을 사용하도록 수정됩니다. `true`

.. * 가용 영역 *: 가용 영역 및 서브넷을 선택합니다.
+
경우에 따라 다릅니다::
+
--
Cluster configuration - Node 1 * 필드에서 * Availability zone * 드롭다운 메뉴에서 가용 영역을 선택하고 * Subnet * 드롭다운 메뉴에서 서브넷을 선택합니다.

--
HA 배포를 위한 것입니다::
+
--
... 클러스터 구성 - 노드 1 * 필드의 * 가용성 영역 * 드롭다운 메뉴에서 MAZ FSx for ONTAP 구성에 대한 기본 사용 가능 영역을 선택하고 * 서브넷 * 드롭다운 메뉴에서 기본 사용 가능 영역의 서브넷을 선택합니다.
... 클러스터 구성 - 노드 2 * 필드에서 * 가용성 영역 * 드롭다운 메뉴에서 MAZ FSx for ONTAP 구성에 대한 보조 가용성 영역을 선택하고 * 서브넷 * 드롭다운 메뉴에서 보조 가용성 영역의 서브넷을 선택합니다.


--


.. * 보안 그룹 *: 기존 보안 그룹을 선택하거나 새 보안 그룹을 만듭니다.
+
새 서버 배포 중에 두 개의 보안 그룹이 SQL 노드(EC2 인스턴스)에 연결됩니다.

+
... PostgreSQL에 필요한 포트 및 프로토콜을 허용하는 워크로드 보안 그룹이 생성됩니다.
... 새로운 FSx for ONTAP 파일 시스템의 경우 새 보안 그룹이 생성되어 SQL 노드에 연결됩니다. 기존 FSx for ONTAP 파일 시스템의 경우 연결된 보안 그룹이 PostgreSQL 노드에 자동으로 추가되어 파일 시스템과의 통신이 가능합니다.




. 응용 프로그램 설정 * 에서 다음을 제공합니다.
+
.. 드롭다운 메뉴에서 * 운영 체제 * 를 선택합니다.
.. 드롭다운 메뉴에서 * PostgreSQL 버전 * 을 선택합니다.
.. * 데이터베이스 서버 이름 *: 데이터베이스 클러스터 이름을 입력합니다.
.. * 데이터베이스 자격 증명 *: 새 서비스 계정에 대한 사용자 이름과 암호를 입력하거나 Active Directory에서 기존 서비스 계정 자격 증명을 사용합니다.


. 연결 * 에서 인스턴스에 안전하게 연결할 키 쌍을 선택합니다.
. 인프라 설정 * 에서 다음을 제공합니다.
+
.. * DB 인스턴스 유형 *: 드롭다운 메뉴에서 데이터베이스 인스턴스 유형을 선택합니다.
.. * FSx for ONTAP 시스템 *: 새로운 FSx for ONTAP 파일 시스템을 생성하거나 기존 FSx for ONTAP 파일 시스템을 사용하십시오.
+
... * 새 FSx for ONTAP 생성 *: 사용자 이름과 암호를 입력합니다.
+
새로운 FSx for ONTAP 파일 시스템은 설치 시간을 30분 이상 추가할 수 있습니다.

... * 기존 FSx for ONTAP 선택 *: 드롭다운 메뉴에서 ONTAP용 FSx 이름을 선택하고 파일 시스템의 사용자 이름과 암호를 입력합니다.
+
기존 FSx for ONTAP 파일 시스템의 경우 다음을 확인하십시오.

+
**** FSx for ONTAP에 연결된 라우팅 그룹을 사용하면 서브넷으로의 경로를 배포에 사용할 수 있습니다.
**** 보안 그룹은 배포에 사용되는 서브넷, 특히 HTTPS(443) 및 iSCSI(3260) TCP 포트의 트래픽을 허용합니다.




.. * 스냅샷 정책 *: 기본적으로 활성화됩니다. 스냅샷은 매일 생성되며 보존 기간은 7일입니다.
+
스냅샷은 PostgreSQL 워크로드를 위해 생성된 볼륨에 할당됩니다.

.. * 데이터 드라이브 크기 * : 데이터 드라이브 용량을 입력하고 용량 단위를 선택하십시오.
.. * 프로비저닝된 IOPS *: * 자동 * 또는 * 사용자 프로비저닝 * 을 선택합니다. User-provisioned * 를 선택한 경우 IOPS 값을 입력합니다.
.. * 처리량 용량 *: 드롭다운 메뉴에서 처리량 용량을 선택합니다.
+
일부 지역에서는 4Gbps의 처리량 용량을 선택할 수 있습니다. 4Gbps의 처리량 용량을 프로비저닝하려면 FSx for ONTAP 파일 시스템을 최소 5,120GiB의 SSD 스토리지 용량과 160,000 SSD IOPS로 구성해야 합니다.

.. * 암호화 *: 계정에서 키를 선택하거나 다른 계정의 키를 선택합니다. 다른 계정의 암호화 키 ARN을 입력해야 합니다.
+
FSx for ONTAP 사용자 지정 암호화 키는 서비스 적용 가능성을 기준으로 나열되지 않습니다. 적절한 FSx 암호화 키를 선택합니다. FSx가 아닌 암호화 키로 인해 서버 생성 오류가 발생합니다.

+
AWS 관리 키는 서비스 적용 가능성에 따라 필터링됩니다.

.. * 태그 * : 선택적으로 최대 40개의 태그를 추가할 수 있습니다.
.. * Simple Notification Service *: 드롭다운 메뉴에서 Microsoft SQL Server에 대한 SNS 항목을 선택하여 이 구성에 대해 SNS(Simple Notification Service)를 활성화할 수 있습니다.
+
... Simple Notification Service를 활성화합니다.
... 드롭다운 메뉴에서 ARN을 선택합니다.


.. * CloudWatch 모니터링 *: 필요에 따라 CloudWatch 모니터링을 활성화할 수 있습니다.
+
오류가 발생할 경우 디버깅을 위해 CloudWatch를 사용하도록 설정하는 것이 좋습니다. AWS CloudFormation 콘솔에 나타나는 이벤트는 상위 수준이며 근본 원인을 지정하지 않습니다. 모든 상세 로그는 `C:\cfn\logs` EC2 인스턴스의 폴더에 저장됩니다.

+
CloudWatch에서 스택의 이름으로 로그 그룹이 생성됩니다. 모든 유효성 검사 노드 및 SQL 노드의 로그 스트림이 로그 그룹 아래에 나타납니다. CloudWatch는 스크립트 진행 상황을 보여 주며 배포 실패 여부와 시기를 이해하는 데 도움이 되는 정보를 제공합니다.

.. * 리소스 롤백 *: 이 기능은 현재 지원되지 않습니다.


. 요약
+
.. *예상 비용*: 표시된 리소스를 배포할 때 발생할 수 있는 예상 비용을 제공합니다.


. Create * 를 클릭하여 새 데이터베이스 호스트를 배포합니다.
+
또는 구성을 저장할 수 있습니다.



.다음 단계
배포된 PostgreSQL 서버에서 사용자, 원격 액세스 및 데이터베이스를 수동으로 구성할 수 있습니다.
