---
sidebar: sidebar 
permalink: detect-host.html 
keywords: detect, detect server instance, instance, detect a database host, instance 
summary: Workload Factory for Databases 에서 Microsoft SQL Server 인스턴스를 감지합니다. 
---
= Microsoft SQL Server 인스턴스를 검색합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases 에서 Microsoft SQL Server 인스턴스를 감지합니다.

이 작업은 _Undetected instance_를 감지하기 위한 것입니다.

.이 작업에 대해
AWS 자격 증명이 Workload Factory에 연결된 경우 데이터베이스를 통해 SQL Server 2016부터 다음과 같은 AWS 스토리지 유형으로 Microsoft SQL Server를 자동으로 검색할 수 있습니다.

* ONTAP용 FSX
* EBS(Elastic Block Store)
* FSx for Windows 파일 서버


데이터베이스에서 검색된 인스턴스는 다음과 같이 분류됩니다.

* _Undetected Instances_: Workload Factory에서 자동으로 검색된 감지되지 않은 인스턴스. 다음과 같은 경우 인스턴스가 감지되지 않습니다.
+
** Microsoft SQL Server 인증에 실패했습니다.
** Microsoft SQL Server용 FSx for ONTAP 파일 시스템이 Workload Factory의 계정에 등록되어 있지 않습니다.


* _관리되지 않는 인스턴스_: 워크로드 팩토리로부터 관리되지 않는 인스턴스를 감지했습니다
* _Managed Instances_: Workload Factory에서 관리하는 인스턴스를 감지했습니다


Workload Factory for Databases에서 Microsoft SQL Server 인스턴스 또는 호스트 인스턴스를 관리하는 첫 번째 단계는 감지되지 않은 데이터베이스 서버 인스턴스를 검색하는 것입니다.

.시작하기 전에
감지되지 않은 데이터베이스 서버 인스턴스를 검색하기 위한 요구 사항은 다음과 같습니다.

* link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정 자격 증명"^]Workload Factory에서 데이터베이스 서버 인스턴스를 감지해야 합니다.
* 인스턴스의 스토리지 유형은 다음 중 하나여야 합니다.
+
** ONTAP용 FSX
** EBS(Elastic Block Store)
** FSx for Windows 파일 서버


* EC2 인스턴스에는 SSM 연결을 감지하기 위해 사용할 수 있는 역할/인스턴스 프로필이 있어야 합니다.
+
Microsoft SQL 인스턴스가 검색되면 기존 환경이 수정되지 않습니다. 감지는 AWS Systems Manager SSM(Session Manager)을 통해 수행됩니다. 우측 IAM 인스턴스 프로필이 없으면 감지가 실패합니다. link:https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-troubleshooting.html["SSM 문제 해결에 대해 자세히 알아보십시오"^]..



.단계
. 에 link:https://console.workloads.netapp.com["워크로드 팩토리 콘솔"^]로그인합니다.
. Databases(데이터베이스) 타일에서 * Go to Databases Inventory(데이터베이스 목록으로 이동) * 를 선택합니다.
. 데이터베이스에서 * Inventory * 탭을 선택합니다.
. 드롭다운 화살표를 클릭하여 검색할 호스트의 행을 확장합니다.
+
호스트가 확장되고 호스트 인스턴스가 나타납니다.

. 검색할 인스턴스의 세 개의 점 메뉴를 클릭합니다.
. 감지 * 를 클릭합니다.
. 인스턴스 감지 * 대화 상자에서 Microsoft SQL Server 사용자 이름 및 암호 또는 FSx for ONTAP 사용자 이름 및 암호를 제공합니다.
+
워크로드 팩토리에서는 Microsoft SQL 자격 증명 또는 FSx for ONTAP 자격 증명을 인증하려고 합니다.

+
이러한 자격 증명 중 하나를 사용할 수 없는 경우 Workload Factory는 PowerShell에 모듈을 설치하려고 `aws.tools.SimpleSystemsManagement` 시도합니다.

. 감지 * 를 클릭합니다.
+
감지된 인스턴스 정보가 나타납니다.

. Yes, Manage instance via Workload Factory * 또는 * No * 를 선택합니다.
. 완료 * 를 클릭합니다.


.다음 단계
호스트 인스턴스의 스토리지 유형이 FSx for ONTAP인 경우 다음을 수행할 수 있습니다 link:manage-server.html["Workload Factory를 통해 인스턴스를 관리합니다"].
