---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 데이터베이스에 대한 BlueXP  워크로드 팩터리에 대한 알려진 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



== 인스턴스 감지 지원

Workload Factory는 Amazon Linux 운영 체제에서만 실행되는 PostgreSQL 인스턴스와 Red Hat Enterprise Linux에서만 실행되는 Oracle 인스턴스를 감지하는 기능을 지원합니다.



== AMI 이미지 버전 지원

각 SQL 버전에 대해 AMI 이미지의 최근 버전 또는 수정본을 최대 4개까지 표시할 수 있습니다. 최신 4개 버전보다 오래된 AMI 이미지에서는 설치할 수 없습니다.



== 사용자 정의 AMI

사용자 지정 AMI를 사용한 배포는 이미지에 설치 미디어가 있는 것으로 가정합니다. 다음과 같은 이유로 FCI 구성에 필요합니다.

* FCI 클러스터를 제거하고 다시 구성하려면 다음을 수행합니다
* 독립 실행형 배포를 위해 이미지의 데이터 정렬 세트 이외의 데이터 정렬을 선택하는 경우


배포의 일부로 워크로드 팩토리에서는 여러 Microsoft SQL Server 인스턴스에 사용자 지정 AMI를 설치하지 않습니다. 기본 Microsoft SQL Server 인스턴스만 배포의 일부로 선택 및 구성됩니다.



== 실패한 배포를 롤백하고 다시 시도하십시오

실패한 배포에 대한 롤백 및 재시도는 작업 부하 공장에서 지원되지 않습니다. AWS의 CloudFormation 콘솔에서 장애가 발생한 스택을 롤백하거나 다시 시도할 수 있습니다.



== Active Directory 및 DNS 리소스 롤백

AWS의 CloudFormation 콘솔에서 테스트를 롤백하거나 배포에 실패한 경우 다음 DNS 리소스가 Active Directory 및 DNS에서 제거되지 않습니다.

* SQL 배포의 각 노드가 관리 IP 주소로 지정됩니다
* FCI의 경우 EC2 인스턴스의 예약된 보조 IP 주소에 대한 Windows 클러스터 이름입니다
* FCI의 두 EC2 인스턴스에서 두 개의 예약된 IP 주소로 SQL FCI 이름을 지정합니다


이러한 항목을 수동으로 정리하거나 도메인이 오래된 항목을 제거할 때까지 기다려야 합니다.



== 상시 가용성 그룹 구성 지원

Always On 가용성 그룹 구성은 워크로드 팩토리에서 지원되지 않습니다.



== 사용자 지정 암호화 키

FSx for ONTAP의 사용자 지정 암호화 키는 서비스 적용 가능성에 따라 나열되지 않습니다. 적절한 키를 선택해야 합니다. AWS 관리 키는 서비스 적용 가능성에 따라 필터링됩니다.



== CloudFormation 템플릿

다운로드하거나 복사한 CodeBox에서 생성된 CloudFormation 템플릿(YAML 파일)의 보존 기간은 7일로 제한됩니다.



== 샌드박스 지원

데이터베이스 서버에서 생성할 수 있는 샌드박스 클론의 최대 수는 90개입니다.



== Microsoft SQL Server 감지 및 관리

Microsoft SQL Server 검색이 저장되지 않았습니다. 작업 부하 공장에서 데이터베이스에 액세스할 때마다 Microsoft SQL Server 감지가 다시 실행되어 해당 지역의 SQL 설치를 식별합니다.



== 비용 절감 효과를

인벤토리 탭에서 각 Microsoft SQL 인스턴스에 대해 표시되는 예상 비용은 SQL 인스턴스를 호스팅하는 볼륨이 아닌 FSx for ONTAP 파일 시스템 수준에서 계산됩니다.



== 여러 FSx for ONTAP 파일 시스템

Workload Factory는 여러 FSx for ONTAP 파일 시스템에서 Microsoft SQL Server에 대한 구성을 생성하거나 저장하는 기능을 지원하지 않습니다. FSx for ONTAP 파일 시스템 구성 배포는 하나만 지원됩니다.



== 최적화 제한 사항



=== 컴퓨팅 적정 사이징 최적화

특정 인스턴스 유형으로 변경할 때 네트워크 구성이 재설정될 수 있으며, 이로 인해 최적화 중에 노드 연결이 실패하고 작업이 실패할 수 있습니다. DNS 설정 및 iSCSI 세션을 확인하고 업데이트하려면 수동 개입이 필요할 수 있습니다. EC2 크기 조정 제한에 대한 자세한 내용은 을 link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resize-limitations.html["Amazon Elastic Compute Cloud 설명서"^]참조하십시오.



=== ONTAP 및 OS 구성 최적화

둘 이상의 SQL Server 인스턴스에 대한 대량 최적화는 ONTAP 구성 및 OS 구성에 지원되지 않습니다.



=== 최적화를 위한 운영 체제 패치 평가

최적화 목적으로 만들어진 운영 체제 패치 평가는 사설 네트워크에서는 작동하지 않을 수 있습니다. 이 평가는 AWS Patch Manager에 의존합니다. 전용 네트워크에서 Windows EC2 인스턴스를 패치하는 방법에 대한 자세한 내용은 을 link:https://aws.amazon.com/blogs/mt/how-to-patch-windows-ec2-instances-in-private-subnets-using-aws-systems-manager/["AWS Cloud Operations 블로그 "AWS Systems Manager를 사용하여 프라이빗 서브넷에서 Windows EC2 인스턴스를 패치하는 방법""^]참조하십시오.



== 온프레미스 비용 절감 계산

Microsoft SQL Server 온-프레미스 스토리지에 대한 볼륨 크기의 비용 및 비율 절감 계산은 고려하지 않습니다.



== 교차 지역 복제 평가

* 대상 FSx for ONTAP 파일 시스템이 다른 AWS 계정에 있는 경우 최적화 평가를 통해 지역 간 복제(CRR)가 사용되고 있는지 확인할 수 없습니다.
* 워크로드 공장에서 소스 FSx for ONTAP 파일 시스템의 CRR 구성만 평가합니다.




== Explore savings에서 데이터베이스 호스트 인증

일부 권한이 제한된 경우, 인증에 성공한 후에도 탐색 저축 페이지가 데이터를 로드하지 않습니다.



== BlueXP backup and recovery 와의 통합

보호를 위해 BlueXP 백업 및 복구에 호스트를 추가한 후, 데이터베이스 검색이 실패하는 경우가 있습니다.
