---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: NetApp Workload Factory for Databases는 최적화, 자동 씬 클로닝, 모니터링 및 해결 기능을 위한 모범 사례가 내장된 종단 간 데이터베이스 배포 및 유지 관리 서비스입니다. 
---
= 데이터베이스용 NetApp Workload Factory에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases는 최적화, 자동 씬 클로닝, 모니터링 및 해결 기능을 위한 모범 사례가 내장된 종단 간 데이터베이스 배포 및 유지 관리 서비스입니다.



== NetApp Workload Factory for Databases란 무엇인가요?

NetApp Workload Factory for Databases는 업계 모범 사례를 준수하는 동시에 성능 및 비용 기대치를 충족하도록 최적화된 Amazon FSx for NetApp ONTAP (FSx for ONTAP) 배포 환경으로 Microsoft SQL Server 데이터를 감지, 평가, 계획, 프로비저닝하고 이동합니다.  NetApp Workload Factory for Databases는 전체 수명 주기 동안 FSx for ONTAP 의 데이터베이스에 대한 지속적인 최적화 및 관리를 제공합니다.

Workload Factory에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Workload Factory 개요"^] .



== 자체 관리형 데이터베이스를 위한 Workload Factory의 이점

Workload Factory는 자체 관리형 데이터베이스에 대한 다음과 같은 유익한 모범 사례와 자동화를 제공합니다.



=== 모범 사례

* AWS Cloud, Microsoft Windows 및 SQL Server, EC2 인스턴스에 NetApp ONTAP for SQL Server 구축으로부터 통합된 지식.
* 총소유비용(TCO)이 최적화된 배치
* AWS, Microsoft 및 ONTAP 모범 사례를 따르는 엔드 투 엔드 배포 자동화
* _빠른 생성_ 배포 모드를 사용하면 수동 구성으로 인해 발생할 수 있는 잠재적인 함정을 피할 수 있습니다.




=== Workload Factory Codebox를 사용한 자동화

Workload Factory는 _Codebox_를 통해 내장된 자동화 기능을 도입했습니다.  Codebox는 다음과 같은 자동화 혜택을 제공합니다.

* * 코드 스니펫 생성 *: 리소스 생성 중에 IAC(Infrastructure-as-Code) 스니펫이 생성되므로 기존 오케스트레이션 워크플로우와의 원활한 통합이 가능합니다.
* *인프라로서의 코드 공동 파일럿*: Codebox는 개발자와 DevOps가 Workload Factory에서 지원하는 모든 작업을 실행하는 코드를 생성하는 데 도움이 되는 인프라로서의 코드(IaC) 공동 파일럿입니다.
* * 코드 뷰어 및 자동화 카탈로그 *: 코드박스는 자동화를 빠르게 분석할 수 있는 코드 뷰어와 빠른 향후 재사용을 위한 자동화 카탈로그를 제공합니다.




=== 데이터베이스용 워크로드 팩토리 기능

Workload Factory for Databases는 다음과 같은 기능을 제공합니다.

* * 간단하고 빠른 배포 *: 사양 질문에 대한 답변을 선택하고 AWS에서 Microsoft SQL Server의 프로비저닝 및 구성 방법을 조사하는 데 일반적으로 필요한 시간을 제거하여 프로비저닝 환경을 간소화하고 간소화합니다.
* *자동 오케스트레이션*: Workload Factory 콘솔에서 _Quick_ 및 _Advanced_ 생성 배포 모드, Chatbot, Codebox를 통한 AWS CloudFormation을 통해 사용 가능합니다.
* * 기본 제공 기능 *: 구축 구성에 내장된 NetApp, Microsoft 및 Amazon 모범 사례 및 AWS 리소스 선택 항목을 활용합니다.
* * 비용 산정 *: Elastic Block Store 및 FSx for Windows File Server를 사용한 기존 Microsoft SQL Server 배포의 스토리지, 컴퓨팅, SQL 라이센스, 스냅샷 및 복제 항목화된 비용을 FSx for ONTAP와 비교하여 추산하는 Savings Calculator로 잠재적인 비용 절감 효과를 평가하십시오.
* *재사용 가능한 자동화 템플릿*: Workload Factory Codebox에서 CloudFormation 템플릿을 만들고, 재사용하고, 사용자 지정하여 여러 환경에서 향후 Microsoft SQL Server를 배포할 수 있습니다.
* * AWS 리소스 검색 및 프로비저닝 *: AWS 계정에서 배포된 FSx for ONTAP, FSx for Windows 파일 서버 및 Elastic Block Store에서 Microsoft SQL 서버를 자동으로 감지합니다. 데이터베이스 인벤토리는 다른 AWS 스토리지 시스템의 서버에 대한 비용 절감 기회를 탐색하거나 FSx for ONTAP 기반 서버 및 인스턴스용 관리 툴을 탐색하기 위한 시작 지점으로 사용됩니다.
* * Sandbox 생성 *: 프로덕션 데이터에 영향을 주지 않고 테스트, 통합, 진단 및 교육에 사용할 수 있는 온디맨드 격리된 데이터베이스 환경을 만듭니다.
* * 데이터베이스 생성 *: 데이터베이스 데이터 정렬, 파일 이름 및 크기를 구성하기 위해 _Quick_or_Advanced_create 모드를 사용하여 기존 Microsoft SQL Server용 사용자 데이터베이스를 생성합니다. 스토리지 구성이 포함되어 있습니다.
* * 작업 모니터링 * : 데이터베이스 작업 실행 진행 상황을 모니터링하고 추적하며 오류가 발생할 경우 문제를 진단하고 해결합니다.
* *지속적인 최적화*: Microsoft SQL Server 자산을 오프라인으로 지속적으로 검사하여 운영 효율성을 높이는 데 도움이 되는 통찰력, 기회 및 권장 사항에 대한 포괄적인 보고서를 제공합니다.




== 자체 관리 데이터베이스에 Amazon FSx for ONTAP의 이점

* * 내구성, 가용성, 안정성 *: FSx for ONTAP는 단일 및 다중 가용성 영역을 지원하는 고가용성, 애플리케이션 인식 스냅샷, 복제를 통한 재해 복구 향상, 효율적인 백업 등 FSx for ONTAP에서 호스팅되는 자가 관리 데이터베이스의 내구성과 가용성을 개선하는 다양한 기능을 제공합니다.
* * 성능 및 확장성 *: FSx for ONTAP는 높은 처리량, 짧은 지연 시간, 고속 네트워크 연결 및 다중 파일 시스템의 확장성을 통해 성능 최적화를 제공하여 워크로드에 필요한 애그리게이트 성능을 확장합니다.
* * 데이터 관리 및 효율성 *: FSx for ONTAP은 공간 효율적인 씬 클론, 씬 프로비저닝, 압축 및 중복제거, 자주 액세스하지 않는 데이터를 용량 풀에 계층화하는 등 데이터 관리 및 효율성을 개선하는 다양한 기능을 제공합니다.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["Workload Factory용 FSx for ONTAP 에 대해 알아보세요"^] .



=== Workload Factory의 운영 모드

_기본_, _읽기 전용_, _읽기/쓰기_의 세 가지 운영 모드는 Workload Factory 내부 및 외부에 배포하기 위한 유연한 옵션을 제공합니다. Workload Factory 외부에서 사용할 수 있는 코드 조각을 통해 _기본_ 모드에서 제로 트러스트에서 즉각적인 가치를 얻으세요. _읽기 전용_ 및 _읽기/쓰기_ 모드에서 증분적 신뢰를 통해 증분적 가치를 얻으세요.

자세히 알아보세요 link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Workload Factory의 운영 모드"^] .



== NetApp Workload Factory를 사용하는 도구

다음 도구와 함께 NetApp Workload Factory를 사용할 수 있습니다.

* *Workload Factory 콘솔*: Workload Factory 콘솔은 애플리케이션과 프로젝트에 대한 시각적이고 전체적인 보기를 제공합니다.
* * NetApp 콘솔*: NetApp 콘솔은 Workload Factory를 다른 NetApp 데이터 서비스와 함께 사용할 수 있도록 하이브리드 인터페이스 환경을 제공합니다.
* *질문하기*: Workload Factory 콘솔을 벗어나지 않고도 Ask me AI 도우미를 사용하여 질문을 하고 Workload Factory에 대해 자세히 알아보세요. Workload Factory 도움말 메뉴에서 Ask me에 액세스하세요.
* *CloudShell CLI*: Workload Factory에는 단일 브라우저 기반 CLI를 통해 여러 계정의 AWS 및 NetApp 환경을 관리하고 운영할 수 있는 CloudShell CLI가 포함되어 있습니다. Workload Factory 콘솔의 상단 표시줄에서 CloudShell에 액세스합니다.
* *REST API*: Workload Factory REST API를 사용하여 FSx for ONTAP 파일 시스템 및 기타 AWS 리소스를 배포하고 관리합니다.
* *CloudFormation*: AWS CloudFormation 코드를 사용하여 Workload Factory 콘솔에서 정의한 작업을 수행하여 AWS 계정의 CloudFormation 스택에서 AWS 및 타사 리소스를 모델링, 프로비저닝 및 관리합니다.
* *Terraform NetApp Workload Factory 공급자*: Terraform을 사용하여 Workload Factory 콘솔에서 생성된 인프라 워크플로를 구축하고 관리합니다.




== 지원되는 구성

Workload Factory는 AWS, NetApp ONTAP, Microsoft SQL Server, Oracle 및 PostgreSQL 모범 사례에 따라 다음과 같은 데이터베이스 엔진, 버전, 운영 체제 및 배포 모델을 지원합니다.

[cols="1,1,1,1"]
|===
| 엔진 | 버전 | 운영 체제 | 배포 모델 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2016 | Windows Server 2016 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2019 | Windows Server 2016 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2022 | Windows Server 2016 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2016 | Windows Server 2019 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2019 | Windows Server 2019 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2022 | Windows Server 2019 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2016 | Windows Server 2022 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2019 | Windows Server 2022 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL Server 2022 | Windows Server 2022 를 참조하십시오 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL 서버 2017 | 어느 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL 서버 2016, 2017, 2019, 2022 | 어느 | FCI, 단일 인스턴스 


| Microsoft SQL Server를 참조하십시오 | SQL 서버 2016, 2019, 2022 | 어느 | 항상 사용 가능한 가용성 그룹 


| 신탁 | 19c | RHEL, SuSe 리눅스 | 독립형(단일/다중 테넌트) 


| 신탁 | 21c | RHEL, SuSe 리눅스 | 독립형(단일/다중 테넌트) 


| 신탁 | 19c | RHEL, SuSe 리눅스 | 독립형(단일/다중 테넌트) 


| 신탁 | 21c | RHEL, SuSe 리눅스 | 독립형(단일/다중 테넌트) 


| 신탁 | 19c | RHEL, SuSe 리눅스 | ASM(단일/멀티 테넌트)과 함께 독립형 


| 신탁 | 21c | RHEL, SuSe 리눅스 | ASM(단일/멀티 테넌트)과 함께 독립형 


| 신탁 | 19c | RHEL, SuSe 리눅스 | 데이터 가드 


| 신탁 | 21c | RHEL, SuSe 리눅스 | 데이터 가드 


| 포스트그레스큐엘 | 포스트그레SQL 15 | 아마존 리눅스 2023 AMI | HA, 독립형 인스턴스 


| 포스트그레스큐엘 | 포스트그레SQL 16 | 아마존 리눅스 2023 AMI | HA, 독립형 인스턴스 
|===


== 통합 AWS 서비스

데이터베이스에는 다음과 같은 통합 AWS 서비스가 포함됩니다.

* CloudFormation 을 참조하십시오
* 간단한 알림 서비스
* 클라우드워치
* System Manager를 참조하십시오
* 비밀 관리자




== 지역

데이터베이스는 FSx for ONTAP가 지원되는 모든 상용 지역에서 지원됩니다. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 아마존 지역을 봅니다."^]

다음 AWS 지역은 지원되지 않습니다.

* 중국 지역
* GovCloud(미국) 지역
* 비밀 클라우드
* 최고 비밀 클라우드




== 도움말 보기

NetApp ONTAP용 Amazon FSx는 AWS 퍼스트 파티 솔루션입니다. 이 서비스를 사용하는 FSx for ONTAP 파일 시스템, 인프라 또는 솔루션과 관련하여 궁금한 사항이나 기술 지원 문제가 있는 경우 AWS 관리 콘솔의 지원 센터를 사용하여 AWS에 지원 케이스를 여십시오. “FSx for ONTAP” 서비스와 적절한 범주를 선택합니다. AWS 지원 케이스를 생성하는 데 필요한 나머지 정보를 제공합니다.

Workload Factory 또는 Workload Factory 애플리케이션 및 서비스에 대한 일반적인 질문은 다음을 참조하세요.link:get-help.html["데이터베이스용 NetApp Workload Factory에 대한 도움말 받기"] .
