---
sidebar: sidebar 
permalink: monitor-databases.html 
keywords: monitor databases, monitor jobs, track database jobs 
summary: 데이터베이스의 워크로드 팩토리 내에서 데이터베이스 작업을 추적하고 데이터베이스를 모니터링합니다. 
---
= 워크로드 팩토리에서 데이터베이스 작업 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터베이스의 워크로드 팩토리 내에서 데이터베이스 작업을 추적하고 데이터베이스를 모니터링합니다.

.이 작업에 대해
데이터베이스는 작업 진행 상황을 추적하고 장애가 발생할 경우 진단 및 문제를 해결할 수 있도록 작업 모니터링을 제공합니다. 유형 및 상태별로 작업을 필터링하고, 검색 기능을 사용하여 작업을 찾고, 작업 테이블을 다운로드할 수 있습니다.

작업 모니터링은 작업에 따라 최대 3가지 수준의 모니터링을 지원합니다. 예를 들어 새 데이터베이스 및 샌드박스 클론 생성을 위해 작업 모니터링은 상위 작업과 하위 작업을 추적합니다.

작업 모니터링 수준::
+
--
* 레벨 1(상위 작업): 호스트 배포 작업을 추적합니다.
* 레벨 2(하위 작업): 호스트 배포 상위 작업과 관련된 하위 작업을 추적합니다.
* 수준 3(작업): 각 자원에 대해 수행된 작업의 순서를 나열합니다.


--
작업 상태입니다:: 작업 모니터링 기능은 _in progress_,_completed_,_completed with issions_, _failed_jobs 일별, 주별, 격주 및 월별로 추적합니다.
작업 이벤트 보존:: 작업 모니터링 이벤트는 사용자 인터페이스에서 30일 동안 유지됩니다.




== 작업을 모니터링합니다

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. 데이터베이스에서 * 작업 모니터링 * 탭을 선택합니다.
. 작업 모니터링 탭에서 필터를 사용하거나 검색을 사용하여 작업 결과를 좁힙니다. 작업 보고서를 다운로드할 수도 있습니다.
. 작업의 세 점 메뉴를 클릭하고 * Go to CloudFormation * 을 클릭하여 AWS CloudFormation 콘솔에서 작업 로그를 확인하십시오.

