---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: BlueXP  Workload Factory for Databases는 Microsoft SQL Server 구성을 스캔하여 운영 효율성을 높이는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= Microsoft SQL Server 배포를 위한 구성 최적화
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터베이스용 BlueXP  워크로드 공장은 Amazon FSx for NetApp ONTAP에서 실행되는 Microsoft SQL 서버 배포 구성을 지속적으로 검사하고 평가합니다. 이 기능은 최적화되지 않은 구성을 자동으로 최적화하여 데이터베이스 워크로드가 탁월한 운영을 달성할 수 있도록 통찰력과 권장 사항을 제공합니다.

.이 작업에 대해
평가는 워크로드 팩토리에서 관리되는 FSx for ONTAP 스토리지를 통해 Microsoft SQL Server 인스턴스에 대해 매일 한 번씩 자동으로 지속적으로 실행됩니다. 평가 보고서는 배포 후 또는 인스턴스 관리 후에 매일 예약된 작업이 실행된 경우에만 최적화 대시보드에서 사용할 수 있습니다.

워크로드 공장 은 FSx for ONTAP 스토리지에 대한 모범 사례를 기반으로 구성을 최적화하기 위한 세부 권장사항을 제공합니다. 권장 사항을 검토하고 최적화되지 않은 구성을 최적화하도록 선택할 수 있습니다.

스캔된 항목:: 워크로드 공장 Microsoft SQL Server 인스턴스에 대한 다음 구성의 최적화 상태를 평가합니다.
+
--
* 스토리지 사이징: 스토리지 계층, 파일 시스템 여유 공간, 로그 드라이브 크기 및 TempDB 드라이브 크기가 포함됩니다
* 스토리지 레이아웃: 사용자 데이터 파일 배치, 로그 파일 배치 및 TempDB 배치가 포함됩니다
* 스토리지 구성: 용량 관리, 씬 프로비저닝, 계층화 정책, 스냅샷, 다중 경로 I/O 상태, 정책 및 세션 등이 포함됩니다
* 컴퓨팅: 적절한 크기 조정, 운영 체제 패치 및 RSS(Receive Side Scaling) 및 TCP 오프로딩과 같은 네트워크 어댑터 설정이 포함됩니다
* 응용 프로그램: Microsoft SQL Server 라이선스, Microsoft SQL Server 패치 및 MAXDOP 설정이 포함됩니다
* 복원력: 로컬 스냅샷, FSx for ONTAP 백업 및 지역 간 복제(CRR) 포함


--


.시작하기 전에
* 읽기 또는 자동화 권한이 있는 자격 증명이 있어야 합니다.
* Microsoft SQL Server 인스턴스의 스토리지를 평가하려면 워크로드 팩토리에서 인스턴스를 관리해야 하고 스토리지 유형이 FSx for ONTAP여야 합니다.
* 설정이나 구성을 최적화하도록 선택하기 전에 각 권장 사항을 주의 깊게 검토하십시오. RSS 및 MAXDOP 설정의 경우 프로덕션 환경을 변경하기 전에 권장 설정을 테스트하여 성능 개선을 확인하는 것이 좋습니다.



NOTE: 최적화 프로세스로 인해 인스턴스 가동 중지 또는 서비스 중단이 발생할 수 있습니다. 구성을 최적화하도록 선택하기 전에 최적화 요약 및 작업 항목을 검토하십시오.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. Inventory * 탭에서 드롭다운 화살표를 선택하여 호스트의 행을 확장하여 관리되는 인스턴스를 봅니다.
+
호스트가 확장되고 호스트 인스턴스가 나타납니다.

. 인스턴스의 세 점 메뉴를 선택한 다음 * 최적화 * 를 선택합니다.
. SQL Server 인스턴스의 인스턴스 최적화 페이지에서 평가 결과를 검토합니다.
+
범주, 하위 범주, 상태, 심각도 및 태그를 기준으로 필터링할 수 있습니다.

+
PDF 내보내기 * 를 선택하여 평가 결과 보고서를 다운로드할 수도 있습니다.

. 드롭다운 화살표를 선택하여 모든 구성에 대한 권장 사항을 확인합니다. 권장 사항을 주의 깊게 검토하십시오.
+
이 권장 사항에서는 최적화되지 않은 구성의 모범 사례와 잠재적 위험을 설명합니다.

. 최적화되지 않은 구성을 * 최적화 * 하려면 선택합니다.
+
* 모두 선택 * 이 기본값이지만 최적화할 특정 리소스를 선택할 수 있습니다.

. 최적화 대화 상자에 나타나는 최적화 요약 및 작업 항목을 검토하여 최적화를 선택하면 어떤 일이 발생할지 알아봅니다. 일부 최적화 작업은 인스턴스 다운 시간 또는 서비스 중단을 일으킬 수 있습니다.
. 구성을 최적화하려면 * Continue * 를 선택하십시오.


.결과
최적화 프로세스가 시작됩니다. 작업 상태를 보려면 * 작업 모니터링 * 탭을 선택하십시오.
