---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 데이터베이스는 Microsoft SQL Server의 스토리지 구성을 스캔하여 운영 효율성을 높이는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= Microsoft SQL Server 배포를 위한 구성 최적화
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터베이스용 BlueXP  워크로드 공장은 Amazon FSx for NetApp ONTAP에서 실행되는 Microsoft SQL 서버 배포 구성을 지속적으로 검사하고 평가합니다. 평가를 통해 통찰력, 권장 사항 및 최적화를 제공하므로 탁월한 운영을 실현할 수 있습니다.

.이 작업에 대해
평가는 워크로드 팩토리에서 관리되는 FSx for ONTAP 스토리지를 통해 Microsoft SQL Server 인스턴스에 대해 매일 한 번씩 자동으로 지속적으로 실행됩니다. 평가 보고서는 배포 후 또는 인스턴스 관리 후에 매일 예약된 작업이 실행된 경우에만 최적화 대시보드에서 사용할 수 있습니다.

워크로드 공장 은 FSx for ONTAP 스토리지에 대한 모범 사례를 기반으로 구성을 최적화하기 위한 세부 권장사항을 제공합니다.

스캔된 항목:: 워크로드 공장 Microsoft SQL Server 인스턴스에 대한 다음 구성의 최적화 상태를 평가합니다.
+
--
* 스토리지 사이징: 스토리지 계층, 파일 시스템 여유 공간, 로그 드라이브 크기 및 TempDB 드라이브 크기가 포함됩니다
* 스토리지 레이아웃: 사용자 데이터 파일 배치, 로그 파일 배치 및 TempDB 배치가 포함됩니다
* 스토리지 구성: 용량 관리, 씬 프로비저닝, 계층화 정책, 스냅샷, 다중 경로 I/O 상태, 정책 및 세션 등이 포함됩니다
* 컴퓨팅: 적합한 크기 조정이 포함됩니다


--


.시작하기 전에
* 읽기 또는 자동화 권한이 있는 자격 증명이 있어야 합니다.
* Microsoft SQL Server 인스턴스의 스토리지를 평가하려면 워크로드 팩토리에서 인스턴스를 관리해야 하고 스토리지 유형이 FSx for ONTAP여야 합니다.
* 설정이나 구성을 최적화하도록 선택하기 전에 각 권장 사항을 주의 깊게 검토하십시오.


.단계
. 에 link:https://console.workloads.netapp.com["워크로드 팩토리 콘솔"^]로그인합니다.
. Databases(데이터베이스) 타일에서 * Go to Databases Inventory(데이터베이스 목록으로 이동) * 를 선택합니다.
. 데이터베이스에서 * Inventory * 탭을 선택합니다.
. 드롭다운 화살표를 클릭하여 호스트의 행을 확장하면 관리되는 인스턴스를 볼 수 있습니다.
+
호스트가 확장되고 호스트 인스턴스가 나타납니다.

. 스캔할 인스턴스의 세 개의 점 메뉴를 선택한 다음 * Optimize * 를 선택합니다.
. 호스트의 인스턴스 최적화 페이지에서 스토리지 평가의 결과를 검토합니다.
+
필터를 사용하여 범주, 하위 범주, 상태, 심각도 및 태그를 기준으로 정렬할 수 있습니다.

+
필요한 경우 * PDF 내보내기 * 를 선택하여 결과 보고서를 다운로드할 수 있습니다.

. 드롭다운 화살표를 선택하여 모든 구성에 대한 권장 사항을 확인합니다. 권장 사항을 주의 깊게 검토하십시오.
+
이 권장 사항에서는 최적화되지 않은 구성의 모범 사례와 잠재적 위험을 설명합니다.

. 최적화되지 않은 구성을 * 최적화 * 하려면 선택합니다.
. 최적화 대화 상자에 나타나는 최적화 요약 및 작업 항목을 검토하여 최적화를 선택하면 어떤 일이 발생할지 알아봅니다. 일부 최적화 작업은 인스턴스 다운 시간 또는 서비스 중단을 일으킬 수 있습니다.
. 구성을 최적화하려면 * Continue * 를 선택하십시오.


.결과
최적화 프로세스가 시작됩니다. 작업 상태를 보려면 * 작업 모니터링 * 탭을 선택하십시오.
