---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: BlueXP  Workload Factory for Databases는 Microsoft SQL Server 구성을 스캔하여 운영 효율성을 높이는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= 워크로드 팩토리에서 잘 설계된 데이터베이스 구성을 구현합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
구성 분석 통찰력과 권장 사항을 활용하여 워크로드 팩토리를 활용하여 데이터베이스 구성에 대한 모범 사례를 구현하세요. 안정성, 보안, 효율성, 성능 및 비용 측면에서 최적화되지 않은 모든 구성의 아키텍처를 쉽게 파악하고 개선 조치를 취할 수 있습니다.

.이 작업에 대해
Workload Factory는 매일 데이터베이스 구성을 분석합니다. 일일 분석은 구성 문제를 자동으로 해결하는 옵션과 함께 통찰력과 권장 사항을 제공하여 구성이 모범 사례를 충족하도록 합니다.

워크로드 팩토리 콘솔 내의 데이터베이스 인벤토리에서 구성 문제에 대한 권장 사항을 검토하고 해당 문제를 해결할 수 있는 옵션이 있습니다.

분석 대상:: 워크로드 팩토리는 Microsoft SQL Server 인스턴스에 대한 다음 구성의 잘 설계된 상태를 분석합니다.
+
--
* 스토리지 사이징: 스토리지 계층, 파일 시스템 여유 공간, 로그 드라이브 크기 및 TempDB 드라이브 크기가 포함됩니다
* 스토리지 레이아웃: 사용자 데이터 파일 배치, 로그 파일 배치 및 TempDB 배치가 포함됩니다
* 스토리지 구성: 용량 관리, 씬 프로비저닝, 계층화 정책, 스냅샷, 다중 경로 I/O 상태, 정책 및 세션 등이 포함됩니다
* 컴퓨팅: 적절한 크기 조정, 운영 체제 패치 및 RSS(Receive Side Scaling) 및 TCP 오프로딩과 같은 네트워크 어댑터 설정이 포함됩니다
* 응용 프로그램: Microsoft SQL Server 라이선스, Microsoft SQL Server 패치 및 MAXDOP 설정이 포함됩니다
* 복원력: 로컬 스냅샷, FSx for ONTAP 백업 및 지역 간 복제(CRR) 포함
* 복제본: 워크로드 팩토리 내부 또는 외부에서 생성되어 60일 이상 지난 복제본(샌드박스)을 새로 고치고 삭제하는 옵션이 포함됩니다.


--


.시작하기 전에
* 당신은 있어야합니다 link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정 자격 증명 및 읽기/쓰기 권한"^] 데이터베이스 구성을 분석합니다.
* Microsoft SQL Server 인스턴스의 저장소를 평가하려면 해당 인스턴스를 워크로드 팩토리에 등록해야 하며 저장소 유형은 FSx for ONTAP이어야 합니다. link:register-instance.html["호스트 인스턴스를 등록하는 방법을 알아보세요."]
* 설정이나 구성을 수정하기 전에 각 권장 사항을 주의 깊게 검토하십시오. RSS 및 MAXDOP 설정의 경우 프로덕션 환경을 변경하기 전에 권장 설정을 테스트하여 성능 개선을 확인하는 것이 좋습니다.



NOTE: 해결 프로세스로 인해 인스턴스 다운타임이나 서비스 중단이 발생할 수 있습니다. 구성을 수정하기로 결정하기 전에 권장 사항을 주의 깊게 검토하세요.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. 인벤토리 * 탭에서 * 인스턴스 * 탭을 선택합니다.
. 인스턴스의 구성 문제를 보려면 *문제 해결*을 선택하세요.
. 호스트 인스턴스의 Well-architected 상태 페이지에서 분석 결과를 검토합니다.
+
구성 문제를 범주, 하위 범주, 상태, 심각도 및 태그별로 필터링할 수 있습니다.

+
*PDF 내보내기*를 선택하면 조사 결과 보고서를 다운로드할 수도 있습니다.

. 드롭다운 화살표를 선택하여 모든 구성에 대한 권장 사항을 확인합니다. 권장 사항에는 모범 사례, 최적화되지 않은 구성의 잠재적 함정, 중요 고려 사항 등이 포함됩니다. 권장 사항을 주의 깊게 검토하십시오.
. 옵션이 제공되는 경우 구성 문제를 *보고 수정*하도록 선택합니다.
+
* 모두 선택 * 이 기본값이지만 최적화할 특정 리소스를 선택할 수 있습니다.

+
.. 복제본 정리를 제외한 모든 구성에 대해 권장 사항 세부 정보를 검토하여 최적화를 선택할 경우 어떤 결과가 발생하는지 확인하세요. 일부 수정 작업으로 인해 인스턴스 다운타임이나 서비스 중단이 발생할 수 있습니다.
.. 클론 정리의 경우 새로 고치거나 삭제할 클론 데이터베이스(샌드박스)를 선택합니다.
+
*** 클론을 새로 고치면 클론을 소스 데이터베이스와 동기화합니다. 워크로드 공장 출하 시 생성된 클론에만 업데이트를 사용할 수 있습니다.
*** 클론을 삭제하면 클론이 영구적으로 제거되고 스토리지 공간이 확보되며 비용이 절감됩니다. 워크로드 공장 내부 및 외부에서 생성된 클론을 삭제할 수 있습니다.




. 구성 문제를 해결하려면 * 계속 * 을 선택하십시오.


.결과
교정 과정이 시작됩니다. 작업 상태를 보려면 * 작업 모니터링 * 탭을 선택하십시오.
