---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: Workload Factory for Databases는 Microsoft SQL Server 및 Oracle 구성을 정기적으로 분석하여 문제가 있는지 확인합니다. 
---
= Workload Factory의 데이터베이스 환경에 대한 구성 분석
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases는 Amazon FSx for NetApp ONTAP 스토리지에 Microsoft SQL Server 및 Oracle을 배포하는 데 문제가 있는지 확인하기 위해 정기적으로 데이터베이스 구성을 분석합니다.  문제가 발견되면 Workload Factory는 문제가 무엇인지 보여주고 데이터베이스 구성에서 최고의 성능, 비용 효율성, 모범 사례 준수를 보장하기 위해 무엇을 변경해야 하는지 설명합니다.

주요 기능은 다음과 같습니다.

* 일일 구성 분석
* 모범 사례 자동 검증
* 적합한 사이징 권장 사항
* 사전 예방적인 관찰 가능성
* 통찰력을 행동으로
* AWS의 잘 설계된 프레임워크 조언자




== 구성 분석의 구성 요소

구성 분석에는 다음 구성 요소가 포함됩니다.

잘 구성된 상태:: 잘 설계된 상태는 데이터베이스 구성의 전반적인 상태를 나타냅니다. 구성은 "최적화됨", "최적화되지 않음", "과도하게 프로비저닝됨"으로 분류됩니다. 잘 설계된 구성 상태는 Workload Factory 콘솔의 Microsoft SQL Server 인스턴스 또는 Oracle 데이터베이스에서 참조됩니다.
잘 짜여진 점수:: 점수에는 현재 분석된 모든 구성이 포함되며 백분율로 표시됩니다. 25% 점수는 데이터베이스 배포의 25%가 잘 설계되었다는 것을 의미합니다. 잘 설계된 점수는 *잘 설계된* 화면과 Workload Factory 콘솔의 Microsoft SQL Server 인스턴스 또는 Oracle 데이터베이스에서 참조됩니다.
구성 범주:: 구성은 스토리지, 컴퓨팅, 애플리케이션, 복원력, 복제라는 범주로 구성됩니다. 각 범주에는 정기적으로 분석되는 구체적인 구성 평가가 포함됩니다. 구성 범주는 *Well-architected* 화면과 Workload Factory 콘솔의 Microsoft SQL Server 인스턴스 또는 Oracle 데이터베이스에서 참조됩니다.




== 분석 범위

최적화 범위는 평가 중인 구성 요소에 따라 다릅니다. 예를 들어, 스토리지 최적화는 SQL 인스턴스 수준에서 이루어지는 반면, 컴퓨팅 최적화는 호스트 레벨에서 이루어집니다.



== 분석 요구 사항

완전한 데이터베이스 환경 분석을 위해서는 리소스를 등록하고 온라인 상태로 유지해야 합니다.

link:register-instance.html["리소스 등록 방법을 알아보세요."]

.다음 단계
link:optimize-configurations.html["잘 설계된 데이터베이스 구성을 구현합니다."]
