---
sidebar: sidebar 
permalink: postpone-analysis.html 
keywords: postpone configuration analysis, dismiss configuration analysis, postpone, dismiss, stop, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 불필요한 경고와 부정확한 최적화 결과를 방지하기 위해 데이터베이스 환경에 적용되지 않는 특정 데이터베이스 구성 분석을 연기하거나 무시합니다. 
---
= 데이터베이스 구성 분석을 연기하거나 해제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
불필요한 경고와 부정확한 최적화 결과를 방지하기 위해 데이터베이스 환경에 적용되지 않는 특정 데이터베이스 구성 분석을 연기하거나 무시합니다. 연기되거나 무시된 구성 해석을 언제든지 다시 활성화할 수 있습니다.

.이 작업에 대해
데이터베이스 구성에 대한 애플리케이션 요구 사항은 서로 다릅니다. Workload Factory는 특정 데이터베이스 구성 분석을 건너뛰는 두 가지 옵션을 제공하므로 관련 문제만 모니터링하고 관련 구성 상태를 정확하게 파악할 수 있습니다. 특정 구성 분석이 연기되거나 무시되면 해당 구성이 총 최적화 점수에 포함되지 않습니다.

구성 수준 및 SQL Server 인스턴스 수준에서 구성 분석을 연기하고, 해제하고, 다시 활성화할 수 있습니다.

* * 30일 연기 *: 분석을 연기하면 30일 동안 분석이 중지됩니다. 30일이 지나면 분석이 자동으로 다시 시작됩니다.
* * Dismiss * : 분석을 해제하면 분석이 무기한 연기됩니다. 필요한 경우 분석을 다시 시작할 수 있습니다.


Microsoft SQL Server 인스턴스에 대해 다음 구성을 연기하거나 해제할 수 있습니다.

* 스토리지 사이징: 스토리지 계층, 파일 시스템 여유 공간, 로그 드라이브 크기 및 TempDB 드라이브 크기가 포함됩니다
* 스토리지 레이아웃: 사용자 데이터 파일 배치, 로그 파일 배치 및 TempDB 배치가 포함됩니다
* 스토리지 구성: 용량 관리, 씬 프로비저닝, 계층화 정책, 스냅샷, 다중 경로 I/O 상태, 정책 및 세션 등이 포함됩니다
* 컴퓨팅: 적절한 크기 조정, 운영 체제 패치 및 RSS(Receive Side Scaling) 및 TCP 오프로딩과 같은 네트워크 어댑터 설정이 포함됩니다
* 응용 프로그램: Microsoft SQL Server 라이선스, Microsoft SQL Server 패치 및 MAXDOP 설정이 포함됩니다
* 복원력: 로컬 스냅샷, FSx for ONTAP 백업 및 지역 간 복제(CRR) 포함
* 복제


다음 지침은 설정 수준에서 해석을 연기하거나, 해제하거나, 다시 활성화하는 방법에 대해 설명합니다. 특정 SQL Server 인스턴스에 대해 다음 작업을 완료하려면 * Dashboard * 탭에서 시작합니다.

[role="tabbed-block"]
====
.연기합니다
구성 분석을 30일간 중지할 수 있습니다. 30일이 지나면 분석이 자동으로 다시 시작됩니다.

--
.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. Inventory *(재고) 탭에서 아래로 스크롤하여 연기할 구성으로 이동한 후 3점 메뉴를 선택한 다음 * 30일 연기 * 를 선택합니다.
. Continue * 를 선택합니다.


.결과
구성 분석이 30일 동안 중지됩니다.

--
.해제
구성 분석을 무기한으로 중지하려면 해제 를 사용합니다. 필요한 경우 분석을 다시 시작할 수 있습니다.

--
.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. Inventory *(재고) 탭에서 해제할 구성을 아래로 스크롤하고 3점 메뉴를 선택한 다음 * Dismiss * 를 선택합니다.
. Continue * 를 선택합니다.


.결과
구성 분석이 중지됩니다.

--
.재활성화
연기되거나 해제된 구성 분석을 언제든지 다시 활성화합니다.

--
.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. Inventory *(재고) 탭에서 재활성화할 구성으로 아래로 스크롤하여 3점 메뉴를 선택한 다음 * Reactivate * 를 선택합니다.
. Continue * 를 선택합니다.


.결과
구성 분석이 다시 활성화되고 매일 앞으로 이동합니다.

--
====