---
sidebar: sidebar 
permalink: protect-sql-server.html 
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database 
summary: Microsoft SQL Server 인스턴스와 데이터베이스를 보호합니다. 
---
= Microsoft SQL Server 워크로드 보호
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
워크로드 팩토리 콘솔에서 BlueXP backup and recovery 사용하여 Microsoft SQL Server 애플리케이션 데이터를 보호하세요. 이 통합을 통해 다음과 같은 보호 목표를 달성할 수 있습니다. 로컬 기본 Amazon FSx for NetApp ONTAP (FSx for ONTAP) 스토리지의 로컬 스냅샷으로 워크로드를 백업하고, 워크로드를 보조 FSx for ONTAP 스토리지로 복제합니다.



== 이 작업에 대해

워크로드 팩토리는 BlueXP backup and recovery 통해 워크로드를 보호할 준비를 하기 위해 리소스 검색, 필수 구성 요소 검증, Microsoft SQL Server용 플러그인 구성 및 설치를 자동화합니다. 이 플러그인은 NetApp 소프트웨어의 호스트 측 구성 요소로, Microsoft SQL Server 워크로드를 보호할 수 있습니다.

BlueXP backup and recovery NetApp SnapMirror 데이터 복제 기술을 활용하여 스냅샷 복사본을 만들고 이를 백업 위치로 전송하여 모든 백업이 완전히 동기화되도록 보장합니다.

BlueXP backup and recovery 통한 보호에 대한 자세한 내용은 다음을 참조하십시오.link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["BlueXP backup and recovery 통한 Microsoft SQL 워크로드 보호 개요"^] .



== 시작하기 전에

BlueXP backup and recovery 사용하여 Microsoft SQL Server 워크로드를 보호하려면 다음 요구 사항을 충족해야 합니다.

* 귀하의 환경이 다음 사항을 충족하는지 확인하십시오.link:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-start-prereq.html#microsoft-sql-server-workload-requirements["BlueXP backup and recovery SQL Server 요구 사항"^] .
* link:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-start-prereq.html#in-bluexp["BlueXP 요구 사항 완료"^]BlueXP, IAM 역할 및 BlueXP 커넥터를 설정하는 것이 포함됩니다.
+
BlueXP 계정에 대한 조직 관리자 액세스 권한이 있는 경우 `backup and recovery super admin` 역할은 자동으로 할당됩니다<<BlueXP backup and recovery 로 보호 준비,BlueXP backup and recovery 로 보호 준비>> .

+
** 커넥터에서 호스트 해상도 설정
+
데이터베이스를 검색하려면 커넥터에서 호스트 확인을 설정해야 합니다.  호스팅된 장치에서 IP 주소 매핑을 호스트 이름에 추가합니다. `/etc/hosts` 파일.



* link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html["BlueXP backup and recovery 에 대한 라이선싱 설정"^]
* 데이터베이스의 워크로드 팩토리에서 Windows 자격 증명을 사용하여 인스턴스를 등록해야 합니다.  Windows 자격 증명을 제공하려면 인벤토리의 인스턴스 탭으로 이동하세요.  인스턴스를 식별하고 *인스턴스 관리*를 선택한 다음 *인스턴스 대시보드*를 선택합니다.  인스턴스 대시보드에서 세 개의 점 메뉴를 선택한 다음 *Microsoft SQL Server 비밀번호 업데이트*를 선택합니다.  Windows 인증을 사용하여 비밀번호를 업데이트합니다.




== BlueXP backup and recovery 로 보호 준비

BlueXP backup and recovery 사용하여 Microsoft SQL Server 리소스를 보호하기 위한 준비 프로세스를 완료하세요.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. 데이터베이스에서 * Inventory * 탭을 선택합니다.
. *엔진 유형*을 *Microsoft SQL Server*로 필터링합니다.
. 보호할 인스턴스의 메뉴에서 *보호*를 선택합니다.
. 워크로드를 등록하고 보호할 *커넥터*를 선택하세요.
. 데이터 보호를 준비하기 위해 Workload Factory는 BlueXP backup and recovery 에 SQL Server 리소스를 자동으로 등록하고, Microsoft SQL Server용 플러그인을 구성 및 설치하고, SQL Server 인스턴스를 보호하기 위한 필수 구성 요소를 충족하는 리소스를 검색합니다.  *시작*을 선택하여 프로세스를 시작하세요.
. 필수 조건을 충족한 후 *리디렉션*을 선택하여 BlueXP backup and recovery 에 액세스하세요.


.다음 단계
BlueXP backup and recovery 통해 Microsoft SQL Server 인스턴스와 데이터베이스를 보호하는 정책을 만듭니다.

link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-policies-create.html["Microsoft SQL Server 인스턴스와 데이터베이스를 보호하는 정책을 만드는 방법을 알아보세요."^] .

관련 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["BlueXP backup and recovery 문서"^] Microsoft SQL Server 작업 부하를 관리합니다.
