---
sidebar: sidebar 
permalink: register-instance.html 
keywords: Microsoft SQL Server instance, PostgreSQL server instance, Oracle host instance, manage host, view host, database host, database instance, manage, unregister 
summary: 데이터베이스용 BlueXP  워크로드 공장에서 Microsoft SQL Server 인스턴스를 관리합니다. 
---
= 데이터베이스의 워크로드 팩토리에 인스턴스 등록
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터베이스의 워크로드 팩토리에서 인스턴스 및 데이터베이스 상태, 리소스 활용도, 보호 및 스토리지 성능을 모니터링할 수 있도록 호스트 인스턴스를 등록합니다.

데이터베이스는 FSx for ONTAP 파일 시스템 스토리지에만 인스턴스를 등록할 수 있습니다.



== 작업에 관하여

호스트 인스턴스를 등록하려면 인스턴스를 인증하고 모든 AWS, NetApp 및 PowerShell 모듈이 인스턴스에 설치되어 있는지 확인하여 인스턴스를 준비하는 두 단계가 필요합니다.

SQL Server 자격 증명이나 Windows 자격 증명을 사용하여 링크를 인증할 수 있습니다.


NOTE: Workload Factory는 Microsoft SQL Server 호스트 인스턴스 등록 및 관리만 지원합니다. Workload Factory에서 선택한 AWS 계정 자격 증명에 따라 PostgreSQL 및 Oracle 호스트가 인벤토리에 나타날 수 있습니다. 현재 Workload Factory는 Amazon Linux 운영 체제에서 실행되는 등록되지 않은 PostgreSQL 인스턴스와 Red Hat Enterprise Linux에서 실행되는 Oracle 인스턴스만 지원합니다.



== 개인 네트워크에 호스트 인스턴스 등록

외부 연결 없이 개인 네트워크에 호스트 인스턴스를 등록하려면 다음 엔드포인트가 SQL 서버가 있는 서브넷과 연결되어 있는 VPC에서 사용 가능해야 합니다. 인터페이스 끝점이 연결된 보안 그룹의 포트 443을 허용하는지 확인합니다.

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`


EC2 인스턴스의 모든 아웃바운드 연결에 프록시 서버를 사용하는 경우 관리 작업이 작동하도록 다음 도메인에 대한 액세스를 허용해야 합니다.

* ``.microsoft.com``
* ``.powershellgallery.com``
* ``.aws.amazon.com``
* ``.amazonaws.com``




== 시작하기 전에

인스턴스의 호스트가 인벤토리 탭에 나타나야 합니다. 호스트가 인벤토리에 나타나려면 link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정 자격 증명과 _읽기 전용_ 또는 _읽기/쓰기_ 모드 권한을 추가해야 합니다."^] .



== 호스트 인스턴스 등록

호스트 인스턴스 등록에는 인스턴스 인증 및 준비가 포함됩니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. 데이터베이스에서 * Inventory * 탭을 선택합니다.
. 인벤토리 탭에서 *인스턴스* 탭을 선택합니다.
. 관리할 인스턴스로 이동하여 *인스턴스 등록*을 선택합니다.
. 인스턴스 등록 페이지에서 SQL Server 사용자 이름과 암호, FSx for ONTAP 파일 시스템 사용자 이름과 암호를 입력합니다.
. 다음 * 을 선택합니다.
. 인스턴스가 필수 전제 조건을 충족하는지 확인하여 인스턴스를 준비합니다. 모든 필수 모듈이 설치되고 전제 조건이 충족되면 *다음*을 선택하여 인스턴스를 등록합니다. 필요한 경우 다음 단계를 따르세요.
+
.. 누락된 경우, 워크로드 팩토리를 선택하여 누락된 AWS 및 NetApp PowerShell 모듈을 설치합니다.
.. 누락된 경우, 워크로드 팩토리를 선택하여 누락된 PowerShell 7을 설치하세요. 누락된 PowerShell 모듈 7을 설치하려면 시스템을 재부팅해야 합니다.
.. 다음 기능에 대한 필수 구성 요소 목록을 검토하세요. 인스턴스를 등록하려면 필수 구성 요소 중 하나를 완료해야 합니다.
+
*** *잘 설계된 문제와 권장 사항을 검토합니다*
*** *잘 설계된 문제 해결*
*** *데이터베이스 생성*
*** *데이터베이스 사본 생성(샌드박스)*
+
필수 조건을 완료하려면 AWS IAM 정책 권한, EC2 IAM 인스턴스 프로필 권한, SQL Server 권한 및 PowerShell 모듈을 업데이트해야 합니다.



.. 계속하려면 최소 하나의 필수 전제 조건을 완료하세요.
.. 하나 이상의 전제 조건이 완료되고 검사가 *준비*되면 인스턴스를 *등록*하도록 선택할 수 있습니다.




.결과
인스턴스 등록 요청이 시작됩니다. 진행 상황을 추적하려면 *작업 모니터링* 탭을 선택하세요.
