---
sidebar: sidebar 
permalink: register-instance.html 
keywords: manage, register, Microsoft SQL Server instance, Oracle database, manage database, manage instance 
summary: NetApp Workload Factory for Databases에서 리소스 상태, 리소스 활용도, 보호 및 스토리지 성능을 모니터링할 수 있도록 리소스를 등록합니다. 
---
= NetApp Workload Factory for Databases에 리소스 등록
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases에서 인스턴스 및 데이터베이스 상태, 리소스 활용도, 보호 및 스토리지 성능을 모니터링할 수 있도록 Microsoft SQL Server 및 Oracle 데이터베이스의 인스턴스를 등록합니다.

FSx for ONTAP 파일 시스템 스토리지에서 실행되는 데이터베이스 엔진에만 등록이 가능합니다.



== 작업에 관하여

인스턴스(SQL Server)나 데이터베이스(Oracle)를 등록하려면 인증과 준비라는 두 단계가 필요합니다.  준비에는 모든 AWS, NetApp 및 PowerShell 모듈이 인스턴스에 설치되어 있는지 확인하는 작업이 포함됩니다.

SQL Server 자격 증명이나 Windows 자격 증명을 사용하여 인증할 수 있습니다.


NOTE: Workload Factory는 Microsoft SQL Server 인스턴스와 Oracle 데이터베이스 등록 및 관리만 지원합니다.  Workload Factory에서 선택한 AWS 계정 자격 증명에 따라 PostgreSQL 호스트가 인벤토리에 나타날 수 있습니다.  현재 Workload Factory는 Amazon Linux 운영 체제에서만 실행되는 등록되지 않은 PostgreSQL 인스턴스만 지원합니다.



== 시작하기 전에

인스턴스를 등록하기 전에 다음 사항을 고려하세요.

인스턴스 또는 데이터베이스의 호스트가 인벤토리에 나타나야 합니다. 호스트가 인벤토리에 나타나려면 다음이 필요합니다. link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["_view, planning 및 analysis_ 권한 부여"^] 귀하의 AWS 계정에서.



=== 개인 네트워크에 인스턴스 등록

외부 연결 없이 개인 네트워크에 인스턴스(SQL Server) 또는 데이터베이스(Oracle)를 등록하려면 다음 엔드포인트가 SQL Server가 있는 서브넷과 연결되어 있는 VPC에서 사용 가능해야 합니다.  인터페이스 엔드포인트가 연결된 보안 그룹에서 포트 443을 허용하는지 확인하세요.

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`
+
EC2 인스턴스의 모든 아웃바운드 연결에 프록시 서버를 사용하는 경우 관리 작업이 작동하도록 다음 도메인에 대한 액세스를 허용해야 합니다.

* ``.microsoft.com``(SQL 서버)
* ``.powershellgallery.com``(SQL 서버)
* ``.aws.amazon.com``
* ``.amazonaws.com``




== SQL Server 인스턴스 등록

인스턴스 등록에는 인스턴스 인증 및 준비가 포함됩니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. 데이터베이스 메뉴에서 *인벤토리*를 선택합니다.
. 인벤토리에서 엔진 유형으로 *Microsoft SQL Server*를 선택합니다.
. *인스턴스* 탭을 선택합니다.
. 단일 인스턴스 또는 여러 인스턴스를 등록할지 선택하세요.
+
.. 단일 인스턴스 등록: 관리할 인스턴스로 이동하여 *인스턴스 등록*을 선택합니다.
.. 다중 인스턴스 등록: *다중 인스턴스 등록* 버튼을 선택하세요.
+
여러 인스턴스를 등록하는 데는 두 가지 옵션이 있습니다. 두 경우 모두 인스턴스는 동일한 인증 상태(인증되지 않음 또는 인증됨)를 공유해야 합니다.

+
*** 인증되지 않은 인스턴스: 등록할 인증되지 않은 인스턴스를 여러 개 선택하세요. 이러한 인스턴스는 동일한 인증 자격 증명과 FSx for ONTAP 자격 증명을 공유해야 합니다. *적용*을 선택한 후 *다음*을 선택하세요.
*** 인증된 인스턴스: 등록할 인증된 인스턴스를 여러 개 선택한 후 *다음*을 선택합니다.




. 인스턴스 등록 페이지의 2단계에서 인스턴스 인증 모드를 선택하고 다음 세부 정보를 입력한 후 *다음*을 선택합니다. 인스턴스가 이미 인증된 경우 *다음*을 선택합니다.
+
** *SQL Server 인증*: SQL Server 사용자 이름과 암호, FSx for ONTAP 파일 시스템 사용자 이름과 암호를 입력합니다.
** *Windows 인증*: Windows 사용자 이름과 비밀번호, FSx for ONTAP 파일 시스템 사용자 이름과 비밀번호를 입력합니다.


. 3단계에서는 인스턴스가 필수 전제 조건을 충족하는지 확인하여 인스턴스를 준비합니다. 모든 필수 모듈이 설치되고 전제 조건이 충족되면 *다음*을 선택하여 인스턴스를 등록합니다. 필요한 경우 다음 단계를 따르세요.
+
.. 누락된 경우, 워크로드 팩토리를 선택하여 누락된 AWS 및 NetApp PowerShell 모듈을 설치합니다.
.. 누락된 경우, 워크로드 팩토리를 선택하여 누락된 PowerShell 7을 설치하세요. 누락된 PowerShell 모듈 7을 설치하려면 시스템을 재부팅해야 합니다.
.. 다음 기능에 대한 필수 구성 요소 목록을 검토하세요.  인스턴스를 등록하려면 기능별 모든 전제 조건을 충족하는지 확인하세요.
+
*** *잘 설계된 문제와 권장 사항을 검토합니다*
*** *잘 설계된 문제 해결*
*** *데이터베이스 생성*
*** *데이터베이스 사본 생성(샌드박스)*
+
필수 조건을 완료하려면 AWS IAM 정책 권한, EC2 IAM 인스턴스 프로필 권한, SQL Server 권한 및 PowerShell 모듈을 업데이트해야 합니다.



.. 필수 구성 요소가 완료되고 검사가 *준비*되면 인스턴스를 *등록*하도록 선택할 수 있습니다.




.결과
인스턴스 등록이 시작됩니다.  진행 상황을 추적하려면 *작업 모니터링* 탭을 선택하세요.



== Oracle 데이터베이스 등록

데이터베이스 등록에는 인스턴스 인증 및 준비가 포함됩니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 데이터베이스 인벤토리로 이동 * 을 선택합니다.
. 데이터베이스 메뉴에서 *인벤토리*를 선택합니다.
. 인벤토리에서 데이터베이스 엔진으로 *Oracle*을 선택합니다.
. *데이터베이스* 탭을 선택합니다.
. 단일 데이터베이스 또는 여러 데이터베이스를 등록할지 선택하세요.
+
.. 단일 데이터베이스 등록: 관리할 데이터베이스로 이동하여 *데이터베이스 등록*을 선택합니다.
.. 여러 데이터베이스 등록: *여러 데이터베이스 등록* 버튼을 선택하세요.
+
여러 데이터베이스를 등록하는 데는 두 가지 옵션이 있습니다.  두 경우 모두 데이터베이스는 동일한 인증 상태(인증되지 않음 또는 인증됨)를 공유해야 합니다.

+
*** 인증되지 않은 데이터베이스: 등록할 인증되지 않은 데이터베이스를 여러 개 선택하세요.  이러한 데이터베이스는 동일한 인증 자격 증명과 FSx for ONTAP 자격 증명을 공유해야 합니다.  *적용*을 선택한 후 *다음*을 선택하세요.
*** 인증된 데이터베이스: 등록할 인증된 데이터베이스를 여러 개 선택한 후 *다음*을 선택합니다.




. 데이터베이스 등록 페이지의 2단계에서 데이터베이스 인증 모드를 선택하고 다음 세부 정보를 입력한 후 *다음*을 선택합니다.  데이터베이스가 이미 인증된 경우 *다음*을 선택합니다.
+
** *Oracle 사용자 인증*: Oracle 사용자 이름과 비밀번호, FSx for ONTAP 파일 시스템 사용자 이름과 비밀번호를 입력합니다.
** *Oracle ASM 사용자 인증*: 선택 사항.  Oracle 데이터베이스가 ASM(자동 스토리지 관리)을 사용하는 경우 Oracle ASM(그리드) 사용자 이름과 비밀번호를 입력합니다.


. 3단계에서는 데이터베이스가 필수 전제 조건을 충족하는지 확인하여 데이터베이스를 준비합니다.  모든 필수 모듈이 설치되고 전제 조건이 충족되면 *다음*을 선택하여 데이터베이스를 등록합니다.  조치를 취해야 하는 경우 다음 단계를 따르세요.
+
.. 다음 기능에 대한 필수 조건 목록을 검토하세요.  데이터베이스를 등록하려면 단일 기능에 대한 모든 전제 조건이 충족되어야 합니다.
+
*** *잘 설계된 문제와 권장 사항을 검토합니다*


.. 다음 전제 조건을 완료하세요.
+
*** *AWS IAM 정책 권한*: AWS 콘솔에서 AWS 권한을 복사하고 업데이트합니다.
*** *EC2 IAM 인스턴스 프로필 권한*: AWS 콘솔에서 Amazon EC2 인스턴스의 EC2 IAM 인스턴스 프로필 권한을 복사하고 업데이트합니다.
*** *배포 모듈*: 필요한 경우 AWS 명령줄 인터페이스(AWS CLI), jq(명령줄 JSON 프로세서), Python 3.12(버전 3.6 이상이 아직 설치되지 않은 경우)를 포함하는 종속 모듈을 설치하도록 선택합니다.  Workload Factory는 등록 과정의 일부로 이러한 모듈을 자동으로 설치합니다.
*** *Oracle 사용자 권한*: 필요한 경우 Oracle 사용자의 권한을 업데이트합니다.


.. 필수 구성 요소가 완료되고 검사가 *준비*되면 데이터베이스를 *등록*하도록 선택할 수 있습니다.




.결과
데이터베이스 등록이 시작됩니다.  진행 상황을 추적하려면 *작업 모니터링* 탭을 선택하세요.

.다음 단계
리소스 등록 후 다음 작업을 수행할 수 있습니다.

* 인벤토리에서 데이터베이스 보기
* link:create-database.html["데이터베이스를 만듭니다"]
* link:create-sandbox-clone.html["데이터베이스 복제본 만들기(샌드박스)"]
* link:optimize-configurations.html["잘 설계된 데이터베이스 구성을 구현합니다."]

