---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, databases, workload factory' 
summary: 데이터베이스용 Workload Factory의 새로운 기능에 대해 알아보십시오. 
---
= 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터베이스의 새로운 기능에 대해 알아봅니다.



== 2024년 8월 4일



=== 비용 절감 계산기 기능 향상

* 비용 추정치 설명
+
이제 비용 절감 계산기에서 비용 추정이 어떻게 계산되는지 알아볼 수 있습니다. Amazon FSx for ONTAP 스토리지를 사용하는 것과 비교하여 Amazon Elastic Block Store 스토리지를 사용하는 Microsoft SQL Server 인스턴스의 모든 계산 설명을 검토할 수 있습니다.

* Always On 가용성 그룹 지원
+
이제 데이터베이스는 Amazon Elastic Block Store를 사용하는 Microsoft SQL Server에서 Always On 가용성 그룹 배포 유형에 대한 비용 절감 계산을 제공합니다.

* FSx for ONTAP으로 SQL 서버 라이센스를 최적화하십시오
+
데이터베이스 계산기는 Amazon Elastic Block Store 스토리지와 함께 사용하는 SQL 라이센스 에디션이 데이터베이스 워크로드에 최적화되었는지 여부를 결정합니다. FSx for ONTAP 스토리지를 사용하는 최적의 SQL 라이센스에 대한 권장사항이 제공됩니다.

* 여러 SQL Server 인스턴스
+
이제 데이터베이스는 Amazon Elastic Block Store를 사용하여 여러 Microsoft SQL Server 인스턴스를 호스팅하는 구성에 대한 비용 절감 계산을 제공합니다.

* 계산기 설정을 사용자 지정합니다
+
이제 Microsoft SQL Server, Amazon EC2 및 Elastic Block Store의 설정을 사용자 지정하여 절감액을 수동으로 탐색할 수 있습니다. 비용 절감 계산기는 비용에 따라 최상의 구성을 결정합니다.



link:explore-savings.html["데이터베이스 워크로드에서 FSx for ONTAP으로 비용 절감 에 대해 알아보십시오."]



== 2024년 7월 7일



=== 데이터베이스용 Workload Factory 초기 릴리즈

초기 릴리즈에는 데이터베이스 워크로드를 위한 스토리지 환경으로 Amazon FSx for NetApp ONTAP을 사용하여 비용 절감을 탐색하고, Microsoft SQL Server를 감지, 관리 및 배포하고, 데이터베이스를 배포 및 복제하고, Workload Factory 내에서 이러한 작업을 모니터링하는 기능이 포함되어 있습니다.

link:learn-databases.html["데이터베이스에 대해 알아봅니다"]..
